GET http://localhost:3000/users/15
Accept: text/html

###

GET http://localhost:3000/

###

POST http://localhost:3000/users

###

POST http://localhost:3000/users/15/nickname
Content-Type: application/json

{
 "nickname": "bar"
}